#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC36CDCB4DF00C68C (infra-root@openstack.org)
#
Name     : bashate
Version  : 0.6.0
Release  : 38
URL      : http://tarballs.openstack.org/bashate/bashate-0.6.0.tar.gz
Source0  : http://tarballs.openstack.org/bashate/bashate-0.6.0.tar.gz
Source1  : http://tarballs.openstack.org/bashate/bashate-0.6.0.tar.gz.asc
Summary  : A pep8 equivalent for bash scripts
Group    : Development/Tools
License  : Apache-2.0
Requires: bashate-bin = %{version}-%{release}
Requires: bashate-license = %{version}-%{release}
Requires: bashate-python = %{version}-%{release}
Requires: bashate-python3 = %{version}-%{release}
Requires: Babel
Requires: pbr
BuildRequires : Babel
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-mock
BuildRequires : python-subunit
BuildRequires : reno-python
BuildRequires : testrepository
BuildRequires : testrepository-python
BuildRequires : tox
BuildRequires : virtualenv

%description
===============================
bashate
===============================

A pep8 equivalent for bash scripts

This program attempts to be an automated style checker for bash scripts
to fill the same part of code review that pep8 does in most OpenStack
projects. It started from humble beginnings in the DevStack project,
and will continue to evolve over time.

The output format aims to follow `pycodestyle (pep8) default output format
<https://github.com/PyCQA/pycodestyle/blob/master/pycodestyle.py#L108>`_.


- Free software: Apache license
- Documentation: https://docs.openstack.org/bashate
- Source: https://git.openstack.org/cgit/openstack-dev/bashate
- Bugs: https://bugs.launchpad.net/bash8

Currently Supported Checks
--------------------------

Errors
~~~~~~

Basic white space errors, for consistent indenting

- E001: check that lines do not end with trailing whitespace
- E002: ensure that indents are only spaces, and not hard tabs
- E003: ensure all indents are a multiple of 4 spaces
- E004: file did not end with a newline
- E005: file does not begin with #! or have a .sh prefix
- E006: check for lines longer than 79 columns

Structure Errors
~~~~~~~~~~~~~~~~

A set of rules that help keep things consistent in control blocks.
These are ignored on long lines that have a continuation, because
unrolling that is kind of "interesting"

- E010: *do* not on the same line as *for*
- E011: *then* not on the same line as *if* or *elif*
- E012: heredoc didn't end before EOF
- E020: Function declaration not in format ``^function name {$``

Obsolete, deprecated or unsafe syntax
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Rules to identify obsolete, deprecated or unsafe syntax that should
not be used

- E040: Syntax errors reported by `bash -n`
- E041: Usage of $[ for arithmetic is deprecated for $((
- E042: local declaration hides errors
- E043: arithmetic compound has inconsistent return semantics
- E044: Use [[ for =~,<,> comparisions

%package bin
Summary: bin components for the bashate package.
Group: Binaries
Requires: bashate-license = %{version}-%{release}

%description bin
bin components for the bashate package.


%package license
Summary: license components for the bashate package.
Group: Default

%description license
license components for the bashate package.


%package python
Summary: python components for the bashate package.
Group: Default
Requires: bashate-python3 = %{version}-%{release}

%description python
python components for the bashate package.


%package python3
Summary: python3 components for the bashate package.
Group: Default
Requires: python3-core
Provides: pypi(bashate)

%description python3
python3 components for the bashate package.


%prep
%setup -q -n bashate-0.6.0
cd %{_builddir}/bashate-0.6.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582849780
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/bashate
cp %{_builddir}/bashate-0.6.0/LICENSE %{buildroot}/usr/share/package-licenses/bashate/57aed0b0f74e63f6b85cce11bce29ba1710b422b
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bashate

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bashate/57aed0b0f74e63f6b85cce11bce29ba1710b422b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
