#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x4F398DEAE440091C (infra-root@openstack.org)
#
Name     : bashate
Version  : 2.0.0
Release  : 39
URL      : http://tarballs.openstack.org/bashate/bashate-2.0.0.tar.gz
Source0  : http://tarballs.openstack.org/bashate/bashate-2.0.0.tar.gz
Source1  : http://tarballs.openstack.org/bashate/bashate-2.0.0.tar.gz.asc
Summary  : A pep8 equivalent for bash scripts
Group    : Development/Tools
License  : Apache-2.0
Requires: bashate-bin = %{version}-%{release}
Requires: bashate-license = %{version}-%{release}
Requires: bashate-python = %{version}-%{release}
Requires: bashate-python3 = %{version}-%{release}
Requires: Babel
Requires: pbr
BuildRequires : Babel
BuildRequires : Sphinx
BuildRequires : Sphinx-python
BuildRequires : buildreq-distutils3
BuildRequires : coverage-python
BuildRequires : discover-python
BuildRequires : hacking
BuildRequires : openstackdocstheme-python
BuildRequires : pbr
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-mock
BuildRequires : python-mock-python
BuildRequires : python-subunit
BuildRequires : reno-python
BuildRequires : stestr
BuildRequires : stestr-python
BuildRequires : tox
BuildRequires : virtualenv

%description
bashate
        ===============================
        
        A pep8 equivalent for bash scripts
        
        This program attempts to be an automated style checker for bash scripts
        to fill the same part of code review that pep8 does in most OpenStack
        projects. It started from humble beginnings in the DevStack project,
        and will continue to evolve over time.
        
        The output format aims to follow `pycodestyle (pep8) default output format

%package bin
Summary: bin components for the bashate package.
Group: Binaries
Requires: bashate-license = %{version}-%{release}

%description bin
bin components for the bashate package.


%package license
Summary: license components for the bashate package.
Group: Default

%description license
license components for the bashate package.


%package python
Summary: python components for the bashate package.
Group: Default
Requires: bashate-python3 = %{version}-%{release}

%description python
python components for the bashate package.


%package python3
Summary: python3 components for the bashate package.
Group: Default
Requires: python3-core
Provides: pypi(bashate)
Requires: pypi(babel)
Requires: pypi(pbr)

%description python3
python3 components for the bashate package.


%prep
%setup -q -n bashate-2.0.0
cd %{_builddir}/bashate-2.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1594658431
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/bashate
cp %{_builddir}/bashate-2.0.0/LICENSE %{buildroot}/usr/share/package-licenses/bashate/57aed0b0f74e63f6b85cce11bce29ba1710b422b
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bashate

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bashate/57aed0b0f74e63f6b85cce11bce29ba1710b422b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
