#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : bashate
Version  : 0.5.1
Release  : 26
URL      : http://tarballs.openstack.org/bashate/bashate-0.5.1.tar.gz
Source0  : http://tarballs.openstack.org/bashate/bashate-0.5.1.tar.gz
Summary  : A pep8 equivalent for bash scripts
Group    : Development/Tools
License  : Apache-2.0
Requires: bashate-bin
Requires: bashate-python
Requires: Babel
Requires: pbr
BuildRequires : configparser-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : virtualenv

%description
===============================
bashate
===============================
A pep8 equivalent for bash scripts

%package bin
Summary: bin components for the bashate package.
Group: Binaries

%description bin
bin components for the bashate package.


%package python
Summary: python components for the bashate package.
Group: Default

%description python
python components for the bashate package.


%prep
%setup -q -n bashate-0.5.1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489280504
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python2.7/site-packages python2 setup.py test || :
%install
export SOURCE_DATE_EPOCH=1489280504
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bashate

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
